##---------------------------------------------------------------------##
## Global parameters
# Dynamic manipulation parameters
stiffness:   ['high_stiffness', 'low_stiffness', 'variable_stiffness']
w_min:       +0.03
w_max:       +0.07
h_mass:      +0.5
path_length: +0.3
bd_min:      -0.3
bd_max:      +0.3
bv_min:      -0.5
bv_max:      +0.5
ba_min:      -2.0
ba_max:      +2.0

##---------------------------------------------------------------------##
## Experiment 0
save_path:   'models/experiment_0/'

# ##---------------------------------------------------------------------##
# ## Experiment 1
# save_path:   'models/experiment_1/'
